@api_id = f5oa9ul0di
@url = https://{{api_id}}.execute-api.us-east-1.amazonaws.com/prod/

POST {{url}} HTTP/1.1
content-type: application/json

{
  "clientId": 134,
  "items": [
    { "productId": 13, "quantity": 2 },
    { "productId": 12, "quantity": 2 }
  ],
  "paymentMethod": "pix",
  "installments": 1
}

###

POST {{url}} HTTP/1.1
content-type: application/json

{
  "clientId": 134,
  "items": [
    { "productId": 17, "quantity": 5 },
    { "productId": 18, "quantity": 1 }
  ],
  "paymentMethod": "cash",
  "installments": 3
}

###

PATCH {{url}}/orders/134/1768747457327403 HTTP/1.1
content-type: application/json

{
  "installments": 3
}

###

GET {{url}}/orders/134 HTTP/1.1

###

GET {{url}}/orders/134?paymentMethod=credit_card HTTP/1.1

###

GET {{url}}/orders/134?paymentMethod=pix HTTP/1.1