@api_id = m1viicgz18
@url = https://{{api_id}}.execute-api.us-east-1.amazonaws.com/prod/

POST {{url}} HTTP/1.1
content-type: application/json

{
  "clientId": 134,
  "items": [
    { "productId": 13, "quantity": 2 },
    { "productId": 12, "quantity": 2 }
  ],
  "paymentMethod": "pix",
  "installments": 1
}

###

POST {{url}} HTTP/1.1
content-type: application/json

{
  "clientId": 134,
  "items": [
    { "productId": 13, "quantity": 2 },
    { "productId": 12, "quantity": 2 }
  ],
  "paymentMethod": "pix",
  "installments": 1
}

###

POST {{url}} HTTP/1.1
content-type: application/json

{
  "clientId": 143,
  "items": [
    { "productId": 27, "quantity": 52 },
    { "productId": 58, "quantity": 10 }
  ],
  "paymentMethod": "credit_card",
  "installments": 12
}

###

POST {{url}} HTTP/1.1
content-type: application/json

{
  "clientId": 143,
  "items": [
    { "productId": 27, "quantity": 52 },
    { "productId": 58, "quantity": 10 }
  ],
  "paymentMethod": "cash",
  "installments": 12
}

###

PATCH {{url}}/orders/134/1768828630327611 HTTP/1.1
content-type: application/json

{
  "installments": 8
}

###

GET {{url}}/orders/134 HTTP/1.1

###

GET {{url}}/orders/134?paymentMethod=credit_card HTTP/1.1

###

GET {{url}}/orders/134?paymentMethod=pix HTTP/1.1

###

GET {{url}}/orders/143?paymentMethod=credit_card HTTP/1.1

###

GET {{url}}/orders/143?paymentMethod=pix HTTP/1.1